// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6.11.2024, 15:36:31
const configMerger = require("C:/Dev/GitProjects/Nuxt/nuxtwebapp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Dev/GitProjects/Nuxt/nuxtwebapp/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","C:/Dev/GitProjects/Nuxt/nuxtwebapp/layouts/**/*.{vue,js,mjs}","C:/Dev/GitProjects/Nuxt/nuxtwebapp/pages/**/*.{vue,js,mjs}","C:/Dev/GitProjects/Nuxt/nuxtwebapp/composables/**/*.{js,ts,mjs}","C:/Dev/GitProjects/Nuxt/nuxtwebapp/utils/**/*.{js,ts,mjs}","C:/Dev/GitProjects/Nuxt/nuxtwebapp/{A,a}pp.{vue,js,mjs}","C:/Dev/GitProjects/Nuxt/nuxtwebapp/{E,e}rror.{vue,js,mjs}","C:/Dev/GitProjects/Nuxt/nuxtwebapp/app.config.{js,ts,mjs}"] }));

module.exports = config
